controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /connexion
    controller: App\Controller\SecurityController::connexion
    methods: ['POST']
